# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-PAO"
BBFILE_PATTERN_meta-PAO = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-PAO = "6"

LAYERDEPENDS_meta-PAO = "core qt6-layer openembedded-layer meta-python raspberrypi"
LAYERSERIES_COMPAT_meta-PAO = "kirkstone"
